### ISSUE TITLE
Test failures in VS

### ISSUE THREAD

**Issue by rainersigwald** [v-fearam/msbuild-examples#3]
In my (int preview) Visual Studio, I get the following test failures:

```
﻿ executeSuccessFail_SettingGenerated
   Source: AppSettingStronglyTypedIntegrationFluentTest.cs line 47
   Duration: 69 ms

  Message: 
Test method AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFail_SettingGenerated threw exception: 
System.TypeLoadException: Could not load type 'Microsoft.Build.Framework.Traits' from assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

  Stack Trace: 
ProjectCollection.ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
ProjectCollection.get_GlobalProjectCollection()
ProjectCreator.Create(String path, String defaultTargets, String initialTargets, String sdk, String toolsVersion, String treatAsLocalProperty, ProjectCollection projectCollection, Nullable`1 projectFileOptions, IDictionary`2 globalProperties)
AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFail_SettingGenerated() line 50
```

```
﻿ executeSuccessFluent_SettingGenerated
   Source: AppSettingStronglyTypedIntegrationFluentTest.cs line 14
   Duration: < 1 ms

  Message: 
Test method AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFluent_SettingGenerated threw exception: 
System.TypeLoadException: Could not load type 'Microsoft.Build.Framework.Traits' from assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

  Stack Trace: 
ProjectCollection.ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
ProjectCollection.get_GlobalProjectCollection()
ProjectCreator.Create(String path, String defaultTargets, String initialTargets, String sdk, String toolsVersion, String treatAsLocalProperty, ProjectCollection projectCollection, Nullable`1 projectFileOptions, IDictionary`2 globalProperties)
AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFluent_SettingGenerated() line 17
```

**Comment by rainersigwald** [comment]
Looks like the same two fail in `dotnet test`:

```sh-session
❯ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AppSettingStronglyTyped -> S:\work\msbuild-examples\custom-task-code-generation\AppSettingStronglyTyped\AppSettingStronglyTyped\bin\Debug\netstandard2.0\AppSettingStronglyTyped.dll
  AppSettingStronglyTyped.Test -> S:\work\msbuild-examples\custom-task-code-generation\AppSettingStronglyTyped\AppSettingStronglyTyped.Test\bin\Debug\net6.0\AppSettingStronglyTyped.Test.dll
Test run for S:\work\msbuild-examples\custom-task-code-generation\AppSettingStronglyTyped\AppSettingStronglyTyped.Test\bin\Debug\net6.0\AppSettingStronglyTyped.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.2.0-preview-20211210-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed executeSuccessFluent_SettingGenerated [56 ms]
  Error Message:
   Test method AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFluent_SettingGenerated threw exception:
System.TypeLoadException: Could not load type 'Microsoft.Build.Framework.Traits' from assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Stack Trace:
      at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Utilities.ProjectCreation.ProjectCreator.Create(String path, String defaultTargets, String initialTargets, String sdk, String toolsVersion, String treatAsLocalProperty, ProjectCollection projectCollection, Nullable`1 projectFileOptions, IDictionary`2 globalProperties)   
   at AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFluent_SettingGenerated() in S:\work\msbuild-examples\custom-task-code-generation\AppSettingStronglyTyped\AppSettingStronglyTyped.Test\AppSettingStronglyTypedIntegrationFluentTest.cs:line 17

  Failed executeSuccessFail_SettingGenerated [< 1 ms]
  Error Message:
   Test method AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFail_SettingGenerated threw exception:
System.TypeLoadException: Could not load type 'Microsoft.Build.Framework.Traits' from assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Stack Trace:
      at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at Microsoft.Build.Utilities.ProjectCreation.ProjectCreator.Create(String path, String defaultTargets, String initialTargets, String sdk, String toolsVersion, String treatAsLocalProperty, ProjectCollection projectCollection, Nullable`1 projectFileOptions, IDictionary`2 globalProperties)   
   at AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFail_SettingGenerated() in S:\work\msbuild-examples\custom-task-code-generation\AppSettingStronglyTyped\AppSettingStronglyTyped.Test\AppSettingStronglyTypedIntegrationFluentTest.cs:line 50


Failed!  - Failed:     2, Passed:    12, Skipped:     0, Total:    14, Duration: 1 s - AppSettingStronglyTyped.Test.dll (net6.0)
```

**Comment by v-fearam** [comment]
To be honest, I can't repro on my end. Works on VS and command line. 
![image](https://user-images.githubusercontent.com/62260324/154107464-2b0ca30f-7886-4783-b5c8-73b00f407e45.png)

I added a dependency to Microsoft.Build.Framework 17

<PackageReference Include="Microsoft.Build.Framework" Version="17.0.0" />

Please, download and try again and let  me know if that fix the issue.

**Comment by v-fearam** [comment]
Good news, I created a VM on Azure and I was able to get similar error 
```
Message: 
Test method AppSettingStronglyTyped.Test.AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFail_SettingGenerated threw exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

  Stack Trace: 
AppSettingStronglyTypedIntegrationFluentTest.executeSuccessFail_SettingGenerated()
```
Bad news, it still happens. I will try to figure out why

**Comment by rainersigwald** [comment]
If you can't crack it quickly, let me know and I'll see if a dev on my team can take a look at it.

**Comment by v-fearam** [comment]
I spent my afternoon and I was not able to solve the issue. I have the VM as repro environment. 
It works on my machine (horrible sentence, I hate it). Based on that, I can't find what allows it work in one machine and not in the another.
Tomorrow I will spend time too, but if someone could take a look, It would be really appreciated.
By the way, I really appreciate your feedback and PR I'm learning a lot :-)

**Comment by v-fearam** [comment]
I have been working all day and I was not able to make it work. 
My suggestion now is to delete the test example related to  https://github.com/jeffkl/MSBuildProjectCreator
I will do it if you agree

**Comment by v-fearam** [comment]
Done, tests were deleted
